/// Generated by AssetsRefGenerator on 2020/03/03
class Res {
  static const String en = "assets/i18n/en.json";
  static const String es = "assets/i18n/es.json";
  static const String pt = "assets/i18n/pt.json";
  static const String icon_inicial = "assets/icon/icon_inicial.png";
  static const String logo_afl = "assets/images/logo_afl.png";
  static const String logo_afl_nova = "assets/images/logo_afl_nova.png";
}
